# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mathieu Tanguy
title: Mecatronic Engineer
email: mathieu@tanguym.eu
address: 11 rue Saint Michel, 44260 Savenay FRANCE
# website: https://mttng.github.io/online-resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mttng
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Full Resume
  icon: fas fa-list
  url: https://cv.tanguym.eu
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Mathieu. I live with my wife and kids near Nantes in France.<br>
  I'm a mecatronic engineer with over 14 years experience in industrial automation.
  <br>
  Since 4 years, I work as a technical office manager for B&R Automation.
  <br>
  I like to work on challenging projects, alone, or as a team. I don't give up so easily.
  I'm creatif and able to listen or understand needs which brings good working relationships with customers or colleagues.
  <br>
  Thanks to my experience working for an innovative supplier, I have a good overview on almost every domain of industrial automation.
  Even though I'm most skilled in:
  <br>
  <mark>Software architecture</mark> <mark>Motion control</mark> <mark>CNC</mark> <mark>Robotic</mark> <mark>IEC 61131-3</mark>

content:
 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B&R Automation
        link: br-automation.com
        # link_text: boringcompany.com
        sub_title: Technical Office Manager
        caption: Feb 2018 - Present (Nantes)
        description: | # this will include new lines to allow paragraphs
            - Lead up to 6 local application & support engineers in Nantes offices.
            - Plan & prioritize technical actions while making sure my team members have enough skills to succeed.
            - Still involved technically in complex strategic customer projects.

      - layout: left
        title: B&R Automation
        link: br-automation.com
        # link_text: boringcompany.com
        sub_title: Application Engineer
        caption: Feb 2010 - Feb 2018 (Paris & Nantes)
        description: | # this will include new lines to allow paragraphs
          - Remote and on-site technical customer support.
          - Assist customer on his project from prototype phase to serial production.
          - Hold customer and internal training.
          - Participate to pre-sales project (presentation, hardware architecture, etc...).

      - layout: left
        title: B&R Automation
        link: https://www.br-automation.com/en/career/working-at-br/engineering-camp/
        link_text: Engineering Camp
        sub_title: Training program
        caption: Sept 2009 - Jan 2010 (Eggelsberg, Austria)
        description: | # this will include new lines to allow paragraphs
          - Attended an engineering camp among talented young people coming from all over the world.
          - I took the opportunity to perfect my knowledge in industrial automation while improving my english.
      - layout: left
        title: TECNAL S.A.
        link: https://www.tecnal.fr/en/home/
        # link_text: boringcompany.com
        sub_title: Automation design office
        caption: Sept 2008 - Aug 2009 (Niort)
        description: | # this will include new lines to allow paragraphs
          - Worked as automation & adjuster technician.
          - I was mainly on the field, either in France or abroad, learning on special machines in process industry.

  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      ### University of Poitiers
      #### caption: 2005 - 2008
      ##### sub_title: MSc in Industrial Automation & mecatronic

      ### University of Lorient
      ### 2003 - 2005
      ###### BTEC in Industrial Maintenance

      ### High School A.R. Lesage in Vannes
      #### 2003
      ##### BD In Mechanical Engineering          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Poitiers
        caption: 2005 - 2008
        sub_title: MSc in Industrial Automation & mecatronic

      - layout: left
        title: University of Lorient
        caption: 2003 - 2005
        sub_title: BTEC in Industrial Maintenance

      - layout: left
        title: High School A.R. Lesage in Vannes
        caption: 2003
        sub_title: BD In Mechanical Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Sports (Running, Mountain Bike, SUP)
      <br>
      Music (Concet, Festival)
      <br>
      domotic and IoT that brings me some basis knowledges on several domains like: 
      <br>
      <mark>Linux</mark> <mark>HTML</mark> <mark>Javascript</mark> <mark>Php</mark> <mark>Docker</mark> <mark>MQTT</mark> <mark>Git</mark> <mark>SQL</mark> 
      <br>

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
